# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fc23f9b03c2f0cd335a593444a631f5ca3878513c577b07452fdf44b388e9e2974bd6cd6b56153a0db00cd8384a30da94963beba1283f3322df7db4564e0eff

test:
  secret_key_base: e95a302c8d50222c32048bbb3d558fa46db1ebda8a9ad514f5415d3c3a4e8a4ee239bd2586be1efe1c00c130ff7517a7df6804c81350193220818c484d372243

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
